update to trunk rev 157

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -472,8 +472,8 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subdirs_all="$ac_subdirs_all ThirdParty/ASL"
 ac_subdirs_all="$ac_subdirs_all ThirdParty/GAMSIO"
+ac_subdirs_all="$ac_subdirs_all ThirdParty/ASL"
 ac_subdirs_all="$ac_subdirs_all ThirdParty/Blas"
 ac_subdirs_all="$ac_subdirs_all ThirdParty/Lapack"
 ac_subdirs_all="$ac_subdirs_all ThirdParty/HSL"
@@ -20629,6 +20629,161 @@ LT_LDFLAGS=
 #             Check which ThirdParty sources are available                  #
 #############################################################################
 
+
+as_ac_File=`echo "ac_cv_file_$srcdir/ThirdParty/GAMSIO/LX3" | $as_tr_sh`
+echo "$as_me:$LINENO: checking for $srcdir/ThirdParty/GAMSIO/LX3" >&5
+echo $ECHO_N "checking for $srcdir/ThirdParty/GAMSIO/LX3... $ECHO_C" >&6
+if eval "test \"\${$as_ac_File+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "$srcdir/ThirdParty/GAMSIO/LX3"; then
+  eval "$as_ac_File=yes"
+else
+  eval "$as_ac_File=no"
+fi
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_File'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_File'}'`" >&6
+if test `eval echo '${'$as_ac_File'}'` = yes; then
+  have_some_gamsiolibs=yes
+else
+   as_ac_File=`echo "ac_cv_file_$srcdir/ThirdParty/GAMSIO/LEI" | $as_tr_sh`
+echo "$as_me:$LINENO: checking for $srcdir/ThirdParty/GAMSIO/LEI" >&5
+echo $ECHO_N "checking for $srcdir/ThirdParty/GAMSIO/LEI... $ECHO_C" >&6
+if eval "test \"\${$as_ac_File+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "$srcdir/ThirdParty/GAMSIO/LEI"; then
+  eval "$as_ac_File=yes"
+else
+  eval "$as_ac_File=no"
+fi
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_File'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_File'}'`" >&6
+if test `eval echo '${'$as_ac_File'}'` = yes; then
+  have_some_gamsiolibs=yes
+else
+   as_ac_File=`echo "ac_cv_file_$srcdir/ThirdParty/GAMSIO/SIG" | $as_tr_sh`
+echo "$as_me:$LINENO: checking for $srcdir/ThirdParty/GAMSIO/SIG" >&5
+echo $ECHO_N "checking for $srcdir/ThirdParty/GAMSIO/SIG... $ECHO_C" >&6
+if eval "test \"\${$as_ac_File+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "$srcdir/ThirdParty/GAMSIO/SIG"; then
+  eval "$as_ac_File=yes"
+else
+  eval "$as_ac_File=no"
+fi
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_File'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_File'}'`" >&6
+if test `eval echo '${'$as_ac_File'}'` = yes; then
+  have_some_gamsiolibs=yes
+else
+   as_ac_File=`echo "ac_cv_file_$srcdir/ThirdParty/GAMSIO/DII" | $as_tr_sh`
+echo "$as_me:$LINENO: checking for $srcdir/ThirdParty/GAMSIO/DII" >&5
+echo $ECHO_N "checking for $srcdir/ThirdParty/GAMSIO/DII... $ECHO_C" >&6
+if eval "test \"\${$as_ac_File+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "$srcdir/ThirdParty/GAMSIO/DII"; then
+  eval "$as_ac_File=yes"
+else
+  eval "$as_ac_File=no"
+fi
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_File'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_File'}'`" >&6
+if test `eval echo '${'$as_ac_File'}'` = yes; then
+  have_some_gamsiolibs=yes
+else
+   as_ac_File=`echo "ac_cv_file_$srcdir/ThirdParty/GAMSIO/VIS" | $as_tr_sh`
+echo "$as_me:$LINENO: checking for $srcdir/ThirdParty/GAMSIO/VIS" >&5
+echo $ECHO_N "checking for $srcdir/ThirdParty/GAMSIO/VIS... $ECHO_C" >&6
+if eval "test \"\${$as_ac_File+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "$srcdir/ThirdParty/GAMSIO/VIS"; then
+  eval "$as_ac_File=yes"
+else
+  eval "$as_ac_File=no"
+fi
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_File'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_File'}'`" >&6
+if test `eval echo '${'$as_ac_File'}'` = yes; then
+  have_some_gamsiolibs=yes
+else
+   have_some_gamsiolibs=no
+fi
+
+
+fi
+
+fi
+
+fi
+
+fi
+
+
+if test x"$have_some_gamsiolibs" = xyes; then
+  echo "$as_me:$LINENO: checking whether code for third party package GAMSIO is available" >&5
+echo $ECHO_N "checking whether code for third party package GAMSIO is available... $ECHO_C" >&6
+coin_skip=no
+if test x"$COIN_SKIP_PROJECTS" != x; then
+  for dir in $COIN_SKIP_PROJECTS; do
+    if test $dir = ThirdParty/GAMSIO; then
+      coin_skip=yes
+    fi
+  done
+fi
+if test $coin_skip = yes; then
+  echo "$as_me:$LINENO: result: skipping" >&5
+echo "${ECHO_T}skipping" >&6
+else
+  coin_tmp=`echo $srcdir/ThirdParty/GAMSIO/get.LX3`
+  # There is probably a more elegant way to get the first thing out here...
+  for i in $coin_tmp; do
+    coin_tmp2=$i
+    #break 1
+  done
+  if test -r $coin_tmp2; then
+    coin_subdirs="$coin_subdirs ThirdParty/GAMSIO"
+    echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+
+subdirs="$subdirs ThirdParty/GAMSIO"
+
+  else
+    echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+  fi
+fi
+
+fi
 echo "$as_me:$LINENO: checking whether code for third party package ASL is available" >&5
 echo $ECHO_N "checking whether code for third party package ASL is available... $ECHO_C" >&6
 coin_skip=no
@@ -20656,40 +20811,6 @@ echo "${ECHO_T}yes" >&6
 
 
 subdirs="$subdirs ThirdParty/ASL"
-
-  else
-    echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-  fi
-fi
-
-echo "$as_me:$LINENO: checking whether code for third party package GAMSIO is available" >&5
-echo $ECHO_N "checking whether code for third party package GAMSIO is available... $ECHO_C" >&6
-coin_skip=no
-if test x"$COIN_SKIP_PROJECTS" != x; then
-  for dir in $COIN_SKIP_PROJECTS; do
-    if test $dir = ThirdParty/GAMSIO; then
-      coin_skip=yes
-    fi
-  done
-fi
-if test $coin_skip = yes; then
-  echo "$as_me:$LINENO: result: skipping" >&5
-echo "${ECHO_T}skipping" >&6
-else
-  coin_tmp=`echo $srcdir/ThirdParty/GAMSIO/get.LX3`
-  # There is probably a more elegant way to get the first thing out here...
-  for i in $coin_tmp; do
-    coin_tmp2=$i
-    #break 1
-  done
-  if test -r $coin_tmp2; then
-    coin_subdirs="$coin_subdirs ThirdParty/GAMSIO"
-    echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-
-
-subdirs="$subdirs ThirdParty/GAMSIO"
 
   else
     echo "$as_me:$LINENO: result: no" >&5
