add OS into externals and LaGO::OSFunction class

diff --git a/LaGO/configure b/LaGO/configure
--- a/LaGO/configure
+++ b/LaGO/configure
@@ -472,7 +472,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os ADDLIBS FADDLIBS ALWAYS_FALSE_TRUE ALWAYS_FALSE_FALSE CDEFS ADD_CFLAGS DBG_CFLAGS OPT_CFLAGS sol_cc_compiler CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT MPICC CXXDEFS ADD_CXXFLAGS DBG_CXXFLAGS OPT_CXXFLAGS CXX CXXFLAGS ac_ct_CXX MPICXX ADD_FFLAGS DBG_FFLAGS OPT_FFLAGS F77 FFLAGS ac_ct_F77 MPIF77 FLIBS EGREP INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LIBTOOLM4 have_autoconf have_automake have_svn BUILDTOOLSDIR AUX_DIR abs_source_dir abs_lib_dir abs_include_dir abs_bin_dir HAVE_EXTERNALS_TRUE HAVE_EXTERNALS_FALSE host host_cpu host_vendor host_os LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP LIBTOOL ac_c_preproc_warn_flag ac_cxx_preproc_warn_flag RPATH_FLAGS LT_LDFLAGS LAGOSRCDIR LAGOOBJDIR LAGODOCDIR COIN_HAS_LAGO_TRUE COIN_HAS_LAGO_FALSE CGLSRCDIR CGLOBJDIR CGLDOCDIR COIN_HAS_CGL_TRUE COIN_HAS_CGL_FALSE COINUTILSSRCDIR COINUTILSOBJDIR COINUTILSDOCDIR COIN_HAS_COINUTILS_TRUE COIN_HAS_COINUTILS_FALSE OSISRCDIR OSIOBJDIR OSIDOCDIR COIN_HAS_OSI_TRUE COIN_HAS_OSI_FALSE IPOPTSRCDIR IPOPTOBJDIR IPOPTDOCDIR COIN_HAS_IPOPT_TRUE COIN_HAS_IPOPT_FALSE CLPSRCDIR CLPOBJDIR CLPDOCDIR COIN_HAS_CLP_TRUE COIN_HAS_CLP_FALSE CBCSRCDIR CBCOBJDIR CBCDOCDIR COIN_HAS_CBC_TRUE COIN_HAS_CBC_FALSE BONMINSRCDIR BONMINOBJDIR BONMINDOCDIR COIN_HAS_BONMIN_TRUE COIN_HAS_BONMIN_FALSE COUENNESRCDIR COUENNEOBJDIR COUENNEDOCDIR COIN_HAS_COUENNE_TRUE COIN_HAS_COUENNE_FALSE CPXINCDIR CPXLIB COIN_HAS_CPX_TRUE COIN_HAS_CPX_FALSE RANLIBC_LIB RANLIBC_CPPFLAGS FILIB_LIB FILIB_CPPFLAGS COIN_HAS_FILIB_TRUE COIN_HAS_FILIB_FALSE gamspath COIN_HAS_GAMSSYSTEM_TRUE COIN_HAS_GAMSSYSTEM_FALSE GAMS_PATH GAMSIO_CODE GAMSIO_CIA GAMSIO_IS_DARWIN_TRUE GAMSIO_IS_DARWIN_FALSE GAMSIO_IS_UNIX_TRUE GAMSIO_IS_UNIX_FALSE GAMSIO_IS_WINDOWS_TRUE GAMSIO_IS_WINDOWS_FALSE GAMSIO_PRESENT_TRUE GAMSIO_PRESENT_FALSE COIN_HAS_GAMSIO_TRUE COIN_HAS_GAMSIO_FALSE COIN_HAS_GAMSIO GAMSIO_CPPFLAGS GAMSIO_ADDLIBS GAMSIO_LIBS SMAG_LIBS GAMSIO_OBJDIR FORTRAN_NAMEMANGLING_CFLAG ASLLIB ASL_CPPFLAGS COIN_HAS_ASL_TRUE COIN_HAS_ASL_FALSE LIBEXT VPATH_DISTCLEANFILES LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os ADDLIBS FADDLIBS ALWAYS_FALSE_TRUE ALWAYS_FALSE_FALSE CDEFS ADD_CFLAGS DBG_CFLAGS OPT_CFLAGS sol_cc_compiler CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT MPICC CXXDEFS ADD_CXXFLAGS DBG_CXXFLAGS OPT_CXXFLAGS CXX CXXFLAGS ac_ct_CXX MPICXX ADD_FFLAGS DBG_FFLAGS OPT_FFLAGS F77 FFLAGS ac_ct_F77 MPIF77 FLIBS EGREP INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LIBTOOLM4 have_autoconf have_automake have_svn BUILDTOOLSDIR AUX_DIR abs_source_dir abs_lib_dir abs_include_dir abs_bin_dir HAVE_EXTERNALS_TRUE HAVE_EXTERNALS_FALSE host host_cpu host_vendor host_os LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP LIBTOOL ac_c_preproc_warn_flag ac_cxx_preproc_warn_flag RPATH_FLAGS LT_LDFLAGS LAGOSRCDIR LAGOOBJDIR LAGODOCDIR COIN_HAS_LAGO_TRUE COIN_HAS_LAGO_FALSE CGLSRCDIR CGLOBJDIR CGLDOCDIR COIN_HAS_CGL_TRUE COIN_HAS_CGL_FALSE COINUTILSSRCDIR COINUTILSOBJDIR COINUTILSDOCDIR COIN_HAS_COINUTILS_TRUE COIN_HAS_COINUTILS_FALSE OSISRCDIR OSIOBJDIR OSIDOCDIR COIN_HAS_OSI_TRUE COIN_HAS_OSI_FALSE IPOPTSRCDIR IPOPTOBJDIR IPOPTDOCDIR COIN_HAS_IPOPT_TRUE COIN_HAS_IPOPT_FALSE CLPSRCDIR CLPOBJDIR CLPDOCDIR COIN_HAS_CLP_TRUE COIN_HAS_CLP_FALSE CBCSRCDIR CBCOBJDIR CBCDOCDIR COIN_HAS_CBC_TRUE COIN_HAS_CBC_FALSE BONMINSRCDIR BONMINOBJDIR BONMINDOCDIR COIN_HAS_BONMIN_TRUE COIN_HAS_BONMIN_FALSE COUENNESRCDIR COUENNEOBJDIR COUENNEDOCDIR COIN_HAS_COUENNE_TRUE COIN_HAS_COUENNE_FALSE CPPADSRCDIR CPPADOBJDIR CPPADDOCDIR COIN_HAS_CPPAD_TRUE COIN_HAS_CPPAD_FALSE OSSRCDIR OSOBJDIR OSDOCDIR COIN_HAS_OS_TRUE COIN_HAS_OS_FALSE CPXINCDIR CPXLIB COIN_HAS_CPX_TRUE COIN_HAS_CPX_FALSE RANLIBC_LIB RANLIBC_CPPFLAGS FILIB_LIB FILIB_CPPFLAGS COIN_HAS_FILIB_TRUE COIN_HAS_FILIB_FALSE gamspath COIN_HAS_GAMSSYSTEM_TRUE COIN_HAS_GAMSSYSTEM_FALSE GAMS_PATH GAMSIO_CODE GAMSIO_CIA GAMSIO_IS_DARWIN_TRUE GAMSIO_IS_DARWIN_FALSE GAMSIO_IS_UNIX_TRUE GAMSIO_IS_UNIX_FALSE GAMSIO_IS_WINDOWS_TRUE GAMSIO_IS_WINDOWS_FALSE GAMSIO_PRESENT_TRUE GAMSIO_PRESENT_FALSE COIN_HAS_GAMSIO_TRUE COIN_HAS_GAMSIO_FALSE COIN_HAS_GAMSIO GAMSIO_CPPFLAGS GAMSIO_ADDLIBS GAMSIO_LIBS SMAG_LIBS GAMSIO_OBJDIR FORTRAN_NAMEMANGLING_CFLAG ASLLIB ASL_CPPFLAGS COIN_HAS_ASL_TRUE COIN_HAS_ASL_FALSE LIBEXT VPATH_DISTCLEANFILES LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -22065,7 +22065,7 @@ fi
 echo "$as_me:$LINENO: result: $coin_has_osi" >&5
 echo "${ECHO_T}$coin_has_osi" >&6
 
-# later: this one is optional, if SNOPT is there
+# later: this one is optional, if another NLP solver is there
 echo "$as_me:$LINENO: checking for COIN project Ipopt" >&5
 echo $ECHO_N "checking for COIN project Ipopt... $ECHO_C" >&6
 
@@ -22355,6 +22355,122 @@ fi
 
 echo "$as_me:$LINENO: result: $coin_has_couenne" >&5
 echo "${ECHO_T}$coin_has_couenne" >&6
+
+echo "$as_me:$LINENO: checking for COIN project cppad" >&5
+echo $ECHO_N "checking for COIN project cppad... $ECHO_C" >&6
+
+# First check, if the sub-project is actually available (ToDo: allow
+# other locations)
+
+coin_has_cppad=unavailable
+if test x"$COIN_SKIP_PROJECTS" != x; then
+  for dir in $COIN_SKIP_PROJECTS; do
+    if test $dir = cppad; then
+      coin_has_cppad=skipping
+    fi
+  done
+fi
+
+if test $coin_has_cppad != skipping; then
+  if test $PACKAGE_TARNAME = cppad; then
+    coin_has_cppad=.
+  else
+    if test -d $srcdir/../cppad; then
+      coin_has_cppad=../cppad
+    fi
+  fi
+fi
+
+if test $coin_has_cppad != unavailable &&
+   test $coin_has_cppad != skipping; then
+  # Set the #define if the component is available
+
+cat >>confdefs.h <<\_ACEOF
+#define COIN_HAS_CPPAD 1
+_ACEOF
+
+
+  # Set the variables for source and object code location
+
+  CPPADSRCDIR=`cd $srcdir/$coin_has_cppad; pwd`
+
+  CPPADOBJDIR=`pwd`/$coin_has_cppad
+
+  CPPADDOCDIR=$abs_lib_dir/../share/doc/coin/cppad
+fi
+
+  # Define the Makefile conditional
+
+
+if test $coin_has_cppad != unavailable &&
+                test $coin_has_cppad != skipping; then
+  COIN_HAS_CPPAD_TRUE=
+  COIN_HAS_CPPAD_FALSE='#'
+else
+  COIN_HAS_CPPAD_TRUE='#'
+  COIN_HAS_CPPAD_FALSE=
+fi
+
+echo "$as_me:$LINENO: result: $coin_has_cppad" >&5
+echo "${ECHO_T}$coin_has_cppad" >&6
+
+echo "$as_me:$LINENO: checking for COIN project OS" >&5
+echo $ECHO_N "checking for COIN project OS... $ECHO_C" >&6
+
+# First check, if the sub-project is actually available (ToDo: allow
+# other locations)
+
+coin_has_os=unavailable
+if test x"$COIN_SKIP_PROJECTS" != x; then
+  for dir in $COIN_SKIP_PROJECTS; do
+    if test $dir = OS; then
+      coin_has_os=skipping
+    fi
+  done
+fi
+
+if test $coin_has_os != skipping; then
+  if test $PACKAGE_TARNAME = os; then
+    coin_has_os=.
+  else
+    if test -d $srcdir/../OS; then
+      coin_has_os=../OS
+    fi
+  fi
+fi
+
+if test $coin_has_os != unavailable &&
+   test $coin_has_os != skipping; then
+  # Set the #define if the component is available
+
+cat >>confdefs.h <<\_ACEOF
+#define COIN_HAS_OS 1
+_ACEOF
+
+
+  # Set the variables for source and object code location
+
+  OSSRCDIR=`cd $srcdir/$coin_has_os; pwd`
+
+  OSOBJDIR=`pwd`/$coin_has_os
+
+  OSDOCDIR=$abs_lib_dir/../share/doc/coin/OS
+fi
+
+  # Define the Makefile conditional
+
+
+if test $coin_has_os != unavailable &&
+                test $coin_has_os != skipping; then
+  COIN_HAS_OS_TRUE=
+  COIN_HAS_OS_FALSE='#'
+else
+  COIN_HAS_OS_TRUE='#'
+  COIN_HAS_OS_FALSE=
+fi
+
+echo "$as_me:$LINENO: result: $coin_has_os" >&5
+echo "${ECHO_T}$coin_has_os" >&6
 
 
 ############################################################################
@@ -26043,8 +26159,6 @@ esac
 # AMPL SOLVER LIBRARY #
 #######################
 
-#LIBS="$LIBS_without_ADDLIBS"
-
 coin_aslobjdir=../ThirdParty/ASL
 coin_aslsrcdir=$srcdir/$coin_aslobjdir
 
@@ -26237,11 +26351,6 @@ fi
 
 
 
-#CPPFLAGS="$ASL_CPPFLAGS $CPPFLAGS"
-#ADDLIBS="$ASLLIB $ADDLIBS"
-
-#AM_CONDITIONAL([COIN_HAS_ASL],[test a=b])
-
 ############
 # END PART #
 ############
@@ -26274,7 +26383,7 @@ if test $coin_vpath_config = yes; then
 fi
 
 
-                                                                                ac_config_files="$ac_config_files Makefile src/Makefile src/Base/Makefile src/Problem/Makefile src/Algorithms/Makefile src/Interfaces/Makefile src/Interfaces/GAMS/Makefile src/Applications/Makefile"
+                                                                                          ac_config_files="$ac_config_files Makefile src/Makefile src/Base/Makefile src/Problem/Makefile src/Algorithms/Makefile src/Interfaces/Makefile src/Interfaces/GAMS/Makefile src/Interfaces/OS/Makefile src/Applications/Makefile"
 
 
           ac_config_headers="$ac_config_headers inc/config_lago.h"
@@ -26530,6 +26639,20 @@ if test -z "${COIN_HAS_COUENNE_TRUE}" && test -z "${COIN_HAS_COUENNE_FALSE}"; th
   { { echo "$as_me:$LINENO: error: conditional \"COIN_HAS_COUENNE\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"COIN_HAS_COUENNE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${COIN_HAS_CPPAD_TRUE}" && test -z "${COIN_HAS_CPPAD_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"COIN_HAS_CPPAD\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"COIN_HAS_CPPAD\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${COIN_HAS_OS_TRUE}" && test -z "${COIN_HAS_OS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"COIN_HAS_OS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"COIN_HAS_OS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -27054,6 +27177,7 @@ do
   "src/Algorithms/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/Algorithms/Makefile" ;;
   "src/Interfaces/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/Interfaces/Makefile" ;;
   "src/Interfaces/GAMS/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/Interfaces/GAMS/Makefile" ;;
+  "src/Interfaces/OS/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/Interfaces/OS/Makefile" ;;
   "src/Applications/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/Applications/Makefile" ;;
   "depfiles" ) CONFIG_COMMANDS="$CONFIG_COMMANDS depfiles" ;;
   "inc/config_lago.h" ) CONFIG_HEADERS="$CONFIG_HEADERS inc/config_lago.h" ;;
@@ -27291,6 +27415,16 @@ s,@COUENNEOBJDIR@,$COUENNEOBJDIR,;t t
 s,@COUENNEDOCDIR@,$COUENNEDOCDIR,;t t
 s,@COIN_HAS_COUENNE_TRUE@,$COIN_HAS_COUENNE_TRUE,;t t
 s,@COIN_HAS_COUENNE_FALSE@,$COIN_HAS_COUENNE_FALSE,;t t
+s,@CPPADSRCDIR@,$CPPADSRCDIR,;t t
+s,@CPPADOBJDIR@,$CPPADOBJDIR,;t t
+s,@CPPADDOCDIR@,$CPPADDOCDIR,;t t
+s,@COIN_HAS_CPPAD_TRUE@,$COIN_HAS_CPPAD_TRUE,;t t
+s,@COIN_HAS_CPPAD_FALSE@,$COIN_HAS_CPPAD_FALSE,;t t
+s,@OSSRCDIR@,$OSSRCDIR,;t t
+s,@OSOBJDIR@,$OSOBJDIR,;t t
+s,@OSDOCDIR@,$OSDOCDIR,;t t
+s,@COIN_HAS_OS_TRUE@,$COIN_HAS_OS_TRUE,;t t
+s,@COIN_HAS_OS_FALSE@,$COIN_HAS_OS_FALSE,;t t
 s,@CPXINCDIR@,$CPXINCDIR,;t t
 s,@CPXLIB@,$CPXLIB,;t t
 s,@COIN_HAS_CPX_TRUE@,$COIN_HAS_CPX_TRUE,;t t
