use trunk revisions of other projects; Applications subdir

diff --git a/LaGO/configure b/LaGO/configure
--- a/LaGO/configure
+++ b/LaGO/configure
@@ -1105,9 +1105,8 @@ Optional Packages:
                           both]
   --with-tags[=TAGS]
                           include additional configurations [automatic]
-  --with-cplex-incdir specify the directory with the header files for library
-                          Cplex
-  --with-cplex-lib specify the flags to link with the library Cplex
+  --with-cplex-incdir specify the header file directory for library Cplex
+  --with-cplex-lib specify the flags used to link with the library Cplex
   --with-filib            specify directory of FILIB++
   --with-gamsio           specify directory of GAMS I/O libraries and header
                           files
@@ -5659,7 +5658,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5662 "configure"' > conftest.$ac_ext
+  echo '#line 5661 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -6793,7 +6792,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:6796:" \
+echo "$as_me:6795:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -7860,11 +7859,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7863: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7862: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7867: \$? = $ac_status" >&5
+   echo "$as_me:7866: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8128,11 +8127,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8131: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8130: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8135: \$? = $ac_status" >&5
+   echo "$as_me:8134: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8232,11 +8231,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8235: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8234: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8239: \$? = $ac_status" >&5
+   echo "$as_me:8238: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10577,7 +10576,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10580 "configure"
+#line 10579 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10677,7 +10676,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10680 "configure"
+#line 10679 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13021,11 +13020,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13024: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13023: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13028: \$? = $ac_status" >&5
+   echo "$as_me:13027: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13125,11 +13124,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13128: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13127: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13132: \$? = $ac_status" >&5
+   echo "$as_me:13131: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14695,11 +14694,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14698: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14697: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14702: \$? = $ac_status" >&5
+   echo "$as_me:14701: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14799,11 +14798,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14802: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14801: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14806: \$? = $ac_status" >&5
+   echo "$as_me:14805: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17006,11 +17005,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17009: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17008: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17013: \$? = $ac_status" >&5
+   echo "$as_me:17012: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17274,11 +17273,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17277: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17276: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17281: \$? = $ac_status" >&5
+   echo "$as_me:17280: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17378,11 +17377,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17381: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17380: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17385: \$? = $ac_status" >&5
+   echo "$as_me:17384: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -23855,25 +23854,30 @@ ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
-echo "$as_me:$LINENO: checking if user provides library for Cplex" >&5
+  echo "$as_me:$LINENO: checking if user provides library for Cplex" >&5
 echo $ECHO_N "checking if user provides library for Cplex... $ECHO_C" >&6
 
 # Check for header file directory
+
 
 # Check whether --with-cplex-incdir or --without-cplex-incdir was given.
 if test "${with_cplex_incdir+set}" = set; then
   withval="$with_cplex_incdir"
   CPXINCDIR=`cd $withval; pwd`
 fi;
+
 # Check for library directory
+
 
 # Check whether --with-cplex-lib or --without-cplex-lib was given.
 if test "${with_cplex_lib+set}" = set; then
   withval="$with_cplex_lib"
   CPXLIB=$withval
 fi;
+
 # Switch to disable library check if requested
-# Check whether --enable-cplex-libcheck or --disable-cplex-libcheck was given.
+
+  # Check whether --enable-cplex-libcheck or --disable-cplex-libcheck was given.
 if test "${enable_cplex_libcheck+set}" = set; then
   enableval="$enable_cplex_libcheck"
   cplex_libcheck=$enableval
@@ -23881,23 +23885,32 @@ else
   cplex_libcheck=yes
 fi;
 
-if test x"$CPXINCDIR" != x || test x"$CPXLIB" != x; then
-  coin_has_cpx=true
-else
-  coin_has_cpx=false
-fi
+# At this point, if we're going to use the library, both LBRYINCDIR and
+# LBRYLIB must be defined and not empty.
 
-if test $coin_has_cpx = true; then
-# Check either both arguments or none are given
-  if test x"$CPXINCDIR" = x || test x"$CPXLIB" = x; then
-    { { echo "$as_me:$LINENO: error: You need to specify both --with-cplex-incdir and --with-cplex-lib if you want to use library Cplex" >&5
-echo "$as_me: error: You need to specify both --with-cplex-incdir and --with-cplex-lib if you want to use library Cplex" >&2;}
+  if test x"$CPXINCDIR" != x || test x"$CPXLIB" != x; then
+    if test x"$CPXINCDIR" = x || test x"$CPXLIB" = x; then
+      { { echo "$as_me:$LINENO: error: You need to specify both an include directory and link flags to use library Cplex. Use --with-cplex-incdir of environment variable $CPXINCDIR to specify the include directory. Use --with-cplex-lib or environment variable $CPXLIB to specify link flags." >&5
+echo "$as_me: error: You need to specify both an include directory and link flags to use library Cplex. Use --with-cplex-incdir of environment variable $CPXINCDIR to specify the include directory. Use --with-cplex-lib or environment variable $CPXLIB to specify link flags." >&2;}
    { (exit 1); exit 1; }; }
-  fi
-  echo "$as_me:$LINENO: result: yes" >&5
+    fi
+    coin_has_cpx=true
+    echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
-  # Check if the given header file is there
-  as_ac_File=`echo "ac_cv_file_$CPXINCDIR/cplex.h" | $as_tr_sh`
+  else
+    coin_has_cpx=false
+    echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+  fi
+
+# If we have instructions for use, consider header and link checks.
+
+  if test $coin_has_cpx = true; then
+
+# If argument 3 (file) is given, check for the file. Typically this will be a
+# header file, but that's not assumed.
+
+    as_ac_File=`echo "ac_cv_file_$CPXINCDIR/cplex.h" | $as_tr_sh`
 echo "$as_me:$LINENO: checking for $CPXINCDIR/cplex.h" >&5
 echo $ECHO_N "checking for $CPXINCDIR/cplex.h... $ECHO_C" >&6
 if eval "test \"\${$as_ac_File+set}\" = set"; then
@@ -23924,32 +23937,37 @@ echo "$as_me: error: Cannot find file cplex.h in $CPXINCDIR" >&2;}
 fi
 
 
-  # Check if the symbol is provided in the library
-  # ToDo: FOR NOW WE ASSUME THAT WE ARE USING THE C++ COMPILER
-  if test x"$cplex_libcheck" != xno; then
-                    coin_save_LIBS="$LIBS"
-                    LIBS="$CPXLIB $ADDLIBS"
-		    echo "$as_me:$LINENO: checking whether symbol CPXgetstat is available with CPX" >&5
-echo $ECHO_N "checking whether symbol CPXgetstat is available with CPX... $ECHO_C" >&6
-                    ac_ext=c
+# Now see if we can link the function. There are arguments for and against
+# assuming argument 3 is a header file declaring the function. A correct
+# function declaration is the main argument in favour. Having to cope with
+# possible dependencies or other oddities are the main arguments against.
+# Force the use of C as the best single choice amongst C++, C, and Fortran.
+# Obviously, this has limits.
+
+    if test x"$cplex_libcheck" != xno; then
+	   coin_save_LIBS="$LIBS"
+	   LIBS="$CPXLIB $ADDLIBS"
+	   coin_CPX_link=no
+	   ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
-# ToDo find out what to do about extern "C"
-#                    AC_TRY_LINK([extern "C" {void CPXgetstat();}],[CPXgetstat()],
-                    cat >conftest.$ac_ext <<_ACEOF
+	   for fnm in CPXgetstat ; do
+	     echo "$as_me:$LINENO: checking whether symbol $fnm is available with CPX" >&5
+echo $ECHO_N "checking whether symbol $fnm is available with CPX... $ECHO_C" >&6
+	     cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-void CPXgetstat();
+
 int
 main ()
 {
-CPXgetstat()
+$fnm()
   ;
   return 0;
 }
@@ -23978,37 +23996,48 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   (exit $ac_status); }; }; then
   echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
+		  coin_CPX_link=yes
+		  break
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
 echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
-                                 { { echo "$as_me:$LINENO: error: Cannot find symbol CPXgetstat with CPX" >&5
-echo "$as_me: error: Cannot find symbol CPXgetstat with CPX" >&2;}
-   { (exit 1); exit 1; }; }
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
-                    ac_ext=c
+	   done
+	   ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
-                    LIBS="$coin_save_LIBS"
-                  fi
+	   if test x"$coin_CPX_link" = xyes ; then
+	     LIBS="$coin_save_LIBS"
+	   else
+	     { { echo "$as_me:$LINENO: error: Cannot find symbol(s) CPXgetstat with CPX" >&5
+echo "$as_me: error: Cannot find symbol(s) CPXgetstat with CPX" >&2;}
+   { (exit 1); exit 1; }; }
+	   fi
+	 fi
 
-  ADDLIBS="$CPXLIB $ADDLIBS"
+
+# If we make it this far, we've verified the file and linked the function. Add
+# the necessary link flags to ADDLIBS and define the preprocessor symbol
+# COIN_HAS_LBRY.
+
+    ADDLIBS="$CPXLIB $ADDLIBS"
 
 cat >>confdefs.h <<\_ACEOF
 #define COIN_HAS_CPX 1
 _ACEOF
 
-else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi
+  fi
+
+# Arrange for configure to substitute LBRYINCDIR and LBRYLIB and create the
+# automake conditional. These actions must occur unconditionally.
 
 
 
@@ -24449,7 +24478,7 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 #AC_COIN_VPATH_LINK(src/install/gmsla_un.dat)
 #AC_COIN_VPATH_LINK(src/install/gmsdu_un.dat)
 
-                              ac_config_files="$ac_config_files Makefile src/Makefile src/Base/Makefile"
+                                        ac_config_files="$ac_config_files Makefile src/Makefile src/Base/Makefile src/Applications/Makefile"
 
 
           ac_config_headers="$ac_config_headers inc/config_lago.h"
@@ -25144,6 +25173,7 @@ do
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
   "src/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/Makefile" ;;
   "src/Base/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/Base/Makefile" ;;
+  "src/Applications/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/Applications/Makefile" ;;
   "depfiles" ) CONFIG_COMMANDS="$CONFIG_COMMANDS depfiles" ;;
   "inc/config_lago.h" ) CONFIG_HEADERS="$CONFIG_HEADERS inc/config_lago.h" ;;
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
